[package]
name = "snowbridge-asset-registry-primitives"
version = "0.1.1"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2018"

[dependencies]
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }

[features]
default = ["std"]
std = ["frame-support/std"]
runtime-benchmarks = []
