[profile.default]
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 20_000
via_ir = false
test = 'contracts/test'
remappings = [
    'ds-test=lib/ds-test/src/',
    'forge-std=lib/forge-std/src/',
    'openzeppelin=lib/openzeppelin-contracts/contracts/',
]
ffi = true
