[workspace]
members = [
    "primitives/core",
    "primitives/ethereum",
    "primitives/testutils",
    "primitives/router",
    "pallets/inbound-queue",
    "pallets/outbound-queue",
    "pallets/outbound-queue/rpc",
    "pallets/outbound-queue/merkle-proof",
    "pallets/router",
    "pallets/ethereum-beacon-client",
    "tools/query-events",
    "tools/call-index"
]
