name: relayer

on:
  push:
    paths:
      - "relayer/**"
    branches:
      - main
  pull_request:
    paths:
      - "relayer/**"

jobs:
  build:
    runs-on: snowbridge-runner
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/checkout@v4
        with:
          go-version: '1.20'

      - name: Check Go version
        run: go version

      - name: Install dependencies
        working-directory: relayer
        run: go mod download

      - name: Install Mage
        working-directory: relayer
        run: go install github.com/magefile/mage@latest

      - name: Run Mage Build Task
        working-directory: relayer
        run: mage build
        env:
          GO111MODULE: on

      - name: Run tests
        working-directory: relayer
        run: go test -v ./...
