name: contracts

on:
  push:
    paths:
      - "relayer/**"
    branches:
      - main
  pull_request:
    paths:
      - "relayer/**"

jobs:
  build:
    runs-on: snowbridge-runner
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -v ./...
