name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: tag (e.g. v1.0) to publish
        required: false

jobs:
  release-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install tools
        run: >
          go install github.com/magefile/mage@v1.15.0 && 
          go install github.com/ferranbt/fastssz/sszgen@v0.1.3
      - name: build
        working-directory: relayer
        run: mage build
      - uses: actions/upload-artifact@v1
        with:
          name: snowbridge-relay
          path: relayer/build/snowbridge-relay

  release-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          docker buildx build \
          --platform linux/amd64 \
          -f relayer/Dockerfile \
          -t "ronyang/snowbridge-relay:${{ github.event.inputs.tag || github.sha }}" \
          . \
          --push
